# Generated by Django 5.1.3 on 2024-12-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='favorite_geners',
            new_name='favorite_genres',
        ),
    ]
